# Generated by Django 4.1.2 on 2022-10-18 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
